[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m coinbase_price_agent.demo_server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "coinbase-demo"

[services.source]
repo = "DMomot/ScoutPay"
rootDirectory = "/"

[variables]
PORT = "8080"
COINBASE_API_KEY = "{{ COINBASE_API_KEY }}"
COINBASE_PRIVATE_KEY = "{{ COINBASE_PRIVATE_KEY }}"
