[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m coinbase_price_agent.x402_server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "coinbase-x402"

[services.source]
repo = "DMomot/ScoutPay"
rootDirectory = "/"

[variables]
PORT = "8080"
COINBASE_API_KEY = "{{ COINBASE_API_KEY }}"
COINBASE_PRIVATE_KEY = "{{ COINBASE_PRIVATE_KEY }}"
X402_WALLET_ADDRESS = "{{ X402_WALLET_ADDRESS }}"
X402_NETWORK = "base"
X402_PRICE = "0.01"
CDP_API_KEY_ID = "{{ CDP_API_KEY_ID }}"
CDP_API_KEY_SECRET = "{{ CDP_API_KEY_SECRET }}"
